image: node:latest

cache:
  paths:
    - node_modules/

staging:
  only:
    - staging
  environment:
    name: staging
  script:
    - npm install -g firebase-tools
    - firebase use staging
    - firebase setup:web --json > firebase-js-config.json
    - npm install
    - npm run build
    - firebase deploy --non-interactive

production:
  only:
    - master
  environment:
    name: production
  script:
    - npm install -g firebase-tools
    - firebase use production
    - firebase setup:web --json > firebase-js-config.json
    - npm install
    - npm run build
    - firebase deploy --token "$FIREBASE_DEPLOY_KEY" --non-interactive
