
language: node_js

node_js:
- 6.9.1

sudo: false

branches:
  only:
    - master
install:
  - npm set progress=false
  - npm install
  - npm install -g firebase-tools

script:
  - npm run build
  - firebase deploy --token "$FIREBASE_TOKEN"